###
GET http://localhost:8081/temperature

###
GET http://localhost:8081/temperature?location=Bedroom

###
GET http://localhost:8081/temperature/3

###
GET http://localhost:8081/actuator/health

###
GET http://localhost:8080/api/v1/sensors



